# Generated by Django 4.0.6 on 2022-08-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deposito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='valor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
