# Generated by Django 4.0.6 on 2022-08-03 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_conta', '0004_remove_conta_gastos'),
        ('app_deposito', '0002_deposito_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_depositos', models.IntegerField()),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conta.conta')),
            ],
        ),
    ]
