# Generated by Django 4.0.6 on 2022-08-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deposito', '0003_contadordeposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='contadordeposito',
            name='valor_ult',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
