# Generated by Django 4.0.6 on 2022-08-03 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_conta', '0004_remove_conta_gastos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trasferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conta.conta')),
            ],
        ),
        migrations.CreateModel(
            name='ContadorTrasferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_trasferencias', models.IntegerField()),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conta.conta')),
            ],
        ),
    ]
